In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv("gen_data/rijeseni-249.csv").drop("id.1",axis =1)
df=df.loc[:, (df != 0).any(axis=0)]
df.head(3)

,id,id_property,category,area,floor,beds_basic,beds_additional,garden,twin_bed,unit_wardrobe_closet,...,hot_water_supply,no_smoking_rooms,in_mini_soccer,special_business,special_groups,unit_bedroom_mosquito_net,mosquito_net,property_internet_location,location_turistcomplex,in_food_local_speciality
0,24588,10043,3,100.0,2,4,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,24589,10043,3,100.0,1,4,2,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,24590,10043,3,100.0,0,4,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0

In [3]:
grps = pd.read_csv("gen_data/facility_togrp.csv").drop("Unnamed: 0",axis=1)
grps.head(3)

         facility_sub_grp         facility_code
0                backyard                garden
1  unit_bedroom_equipment              twin_bed
2  unit_bedroom_equipment  unit_wardrobe_closet

In [4]:
#iz grps je potrebno izbaciti sve kodove koji nisu u df
fcodes = df.columns[7:]

no_grp=[]
grp_df = pd.DataFrame(columns = ["facility_sub_grp", "facility_code"])
for index,i in enumerate(fcodes):
    try:
        grp_df.loc[index] = [grps[grps["facility_code"]==i]["facility_sub_grp"].dropna().unique().tolist()[0],i]
    except:
        no_grp.append(i)
    
grp_df.shape

(173, 2)

In [5]:
grp_df.head()

         facility_sub_grp               facility_code
0                backyard                      garden
1  unit_bedroom_equipment                    twin_bed
2  unit_bedroom_equipment        unit_wardrobe_closet
3  unit_bedroom_equipment  unit_bedroom_parquet_floor
4                 kitchen                refrigerator

## Potrebno na dijelu napravit PCA a dio bez grupa grupirat ili zadrzat - 
## spremljeno u no_grp

In [6]:
grps[grps["facility_code"]=="sattv"]

Empty DataFrame
Columns: [facility_sub_grp, facility_code]
Index: []

In [7]:
grp_df
#no_grp

           facility_sub_grp               facility_code
0                  backyard                      garden
1    unit_bedroom_equipment                    twin_bed
2    unit_bedroom_equipment        unit_wardrobe_closet
3    unit_bedroom_equipment  unit_bedroom_parquet_floor
4                   kitchen                refrigerator
..                      ...                         ...
236     sg_reservation_cond              special_groups
237  unit_bedroom_equipment   unit_bedroom_mosquito_net
239    property_sg_internet  property_internet_location
240             sg_location      location_turistcomplex
241                 sg_food    in_food_local_speciality

[173 rows x 2 columns]

In [8]:
grps[grps["facility_sub_grp"]=="backyard"]["facility_code"].tolist()

['garden',
 'use_grill',
 'in_garden_forniture',
 'outside_area_completely_enclosed']

In [9]:
grp_list = grp_df["facility_sub_grp"].unique()

In [10]:
# 2- category 3-area 4 - floor i 6-beds additional potrebno skalirat kao ostale features
new_df = df.loc[:,df.columns[0:6]]
new_df

         id  id_property  category   area  floor  beds_basic
0     24588        10043         3  100.0      2           4
1     24589        10043         3  100.0      1           4
2     24590        10043         3  100.0      0           4
3     24593        10046         3   53.0      0           4
4     24594         9098         3   65.0      0           4
...     ...          ...       ...    ...    ...         ...
1846  24569        10032         3   95.0      2           6
1847  24570        10033         3   45.0      1           2
1848  24571        10034         5  150.0      0           6
1849  24572        10035         5  150.0      0           6
1850  24575        10039         4  178.0      0           6

[1851 rows x 6 columns]

In [11]:
#scikit learn.decomposition
df.columns[7:]

Index(['garden', 'twin_bed', 'unit_wardrobe_closet',
       'unit_bedroom_parquet_floor', 'refrigerator', 'dishes', 'oven_pu',
       'freezing_compartment', 'dishwasher', 'microwave',
       ...
       'hot_water_supply', 'no_smoking_rooms', 'in_mini_soccer',
       'special_business', 'special_groups', 'unit_bedroom_mosquito_net',
       'mosquito_net', 'property_internet_location', 'location_turistcomplex',
       'in_food_local_speciality'],
      dtype='object', length=242)

In [12]:
"""def PCA(ls):
    pass"""

'def PCA(ls):\n    pass'

In [13]:
scaler = StandardScaler()
X=df.loc[:,df.columns[6:]]
scaler.fit(X)

scale_ar = scaler.transform(X)
len(df.columns)
#len(scale_df[0])

249

In [14]:
scale_ar

array([[ 1.15969235,  1.23222049,  0.68827764, ..., -0.02324953,
        -0.10451312, -0.0465368 ],
       [ 1.15969235,  1.23222049,  0.68827764, ..., -0.02324953,
        -0.10451312, -0.0465368 ],
       [-1.02847334,  1.23222049,  0.68827764, ..., -0.02324953,
        -0.10451312, -0.0465368 ],
       ...,
       [-1.02847334,  1.23222049,  0.68827764, ..., -0.02324953,
        -0.10451312, -0.0465368 ],
       [-1.02847334,  1.23222049,  0.68827764, ..., -0.02324953,
        -0.10451312, -0.0465368 ],
       [-1.02847334,  1.23222049,  0.68827764, ..., -0.02324953,
        -0.10451312, -0.0465368 ]])

,id,id_property,category,area,floor,beds_basic,beds_additional,garden,twin_bed,unit_wardrobe_closet,...,hot_water_supply,no_smoking_rooms,in_mini_soccer,special_business,special_groups,unit_bedroom_mosquito_net,mosquito_net,property_internet_location,location_turistcomplex,in_food_local_speciality
0,24588,10043,3,100.0,2,4,1.159692,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
1,24589,10043,3,100.0,1,4,1.159692,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
2,24590,10043,3,100.0,0,4,-1.028473,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
3,24593,10046,3,53.0,0,4,-1.028473,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
4,24594,9098,3,65.0,0,4,0.065610,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1846,24569,10032,3,95.0,2,6,-1.028473,-0.811543,-1.452902,-1.980624,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
1847,24570,10033,3,45.0,1,2,1.159692,-0.811543,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
1848,24571,10034,5,150.0,0,6,-1.028473,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
1849,24572,10035,5,150.0,0,6,-1.028473,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537
1850,24575,10039,4,178.0,0,6,-1.028473,1.232220,0.688278,0.504891,...,-0.040291,-0.052044,-0.02325,-0.032889,-0.02325,-0.046537,-0.040291,-0.02325,-0.104513,-0.046537

In [16]:
"""codes = grp_df[grp_df["facility_sub_grp"]=="backyard"]["facility_code"].tolist()
val = df[codes].values
pca = PCA(n_components=)
"""

'codes = grp_df[grp_df["facility_sub_grp"]=="backyard"]["facility_code"].tolist()\nval = df[codes].values\npca = PCA(n_components=)\n'

In [17]:
len(grp_list)

47

In [18]:
exception=[]
for i in grp_list:
    codes = grp_df[grp_df["facility_sub_grp"]==i]["facility_code"].tolist()
    n_comp = len(codes)
    pca = PCA(n_components=1)
    pca.fit(df[codes].values)
    new_df[i] = pca.transform(df[codes])
 
""" try:
        #new_df[i]= PCA(df[codes])
        pca = PCA()
        pca.fit(df[codes])
        new_df[i] = pca.transform(df[codes])
    except:
        exception.append(i)"""

C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
C:\Users\Korisnik\anaconda3\envs\AGprojekt\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(

' try:\n        #new_df[i]= PCA(df[codes])\n        pca = PCA()\n        pca.fit(df[codes])\n        new_df[i] = pca.transform(df[codes])\n    except:\n        exception.append(i)'

In [19]:
new_df.head()

,id,id_property,category,area,floor,beds_basic,backyard,unit_bedroom_equipment,kitchen,unit_bathroom_equipment,...,children,main,health,sport_zabava,public_pools,disg_sea,property_city_tax,sg_hot_water,property_sg_internet,sg_food
0,24588,10043,3,100.0,2,4,0.359911,-0.612327,0.397342,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
1,24589,10043,3,100.0,1,4,0.359911,-0.612327,-0.126305,0.314040,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
2,24590,10043,3,100.0,0,4,0.359911,-0.612327,0.295777,-0.261960,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
3,24593,10046,3,53.0,0,4,0.359911,0.006103,0.051845,-0.261960,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
4,24594,9098,3,65.0,0,4,0.359911,-0.731971,-0.262609,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161

In [20]:
exception

[]

In [21]:
new_df.head(30)

,id,id_property,category,area,floor,beds_basic,backyard,unit_bedroom_equipment,kitchen,unit_bathroom_equipment,...,children,main,health,sport_zabava,public_pools,disg_sea,property_city_tax,sg_hot_water,property_sg_internet,sg_food
0,24588,10043,3,100.0,2,4,0.359911,-0.612327,0.397342,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
1,24589,10043,3,100.0,1,4,0.359911,-0.612327,-0.126305,0.314040,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
2,24590,10043,3,100.0,0,4,0.359911,-0.612327,0.295777,-0.261960,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
3,24593,10046,3,53.0,0,4,0.359911,0.006103,0.051845,-0.261960,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
4,24594,9098,3,65.0,0,4,0.359911,-0.731971,-0.262609,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
5,24595,10047,3,190.0,0,8,0.911876,-0.112599,-0.753046,-0.135815,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
6,24597,10049,4,62.0,3,4,-0.473952,-0.612327,-0.781679,-0.245530,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
7,24598,10049,4,40.0,3,2,-0.473952,-0.612327,-0.201444,-0.245530,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
8,24604,10054,3,55.0,0,4,0.359911,-0.612327,-0.520545,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
9,24607,10055,3,60.0,0,2,-0.473952,-0.731971,-0.903934,0.457724,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
10,24608,10056,3,40.0,2,2,0.359911,-0.612327,-0.505962,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
11,24609,10056,3,30.0,2,2,0.359911,0.450717,-0.098463,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
12,24610,10056,3,40.0,3,2,0.359911,-0.612327,-0.098463,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
13,24611,10056,3,30.0,3,2,0.359911,0.331073,-0.098463,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
14,24612,10056,3,70.0,1,8,0.359911,-0.731971,-0.928045,0.380093,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
15,24613,10056,3,50.0,0,4,0.359911,-0.612327,-0.708802,-0.018159,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
16,24614,10057,3,140.0,0,8,0.911876,-0.612327,-1.153280,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
17,24616,10058,4,29.0,1,2,0.911876,-0.731971,1.658724,-0.001729,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
18,24617,10058,4,29.0,2,2,0.911876,-0.731971,1.658724,-0.001729,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
19,24618,10058,4,28.0,1,2,0.911876,-0.731971,1.326969,-0.001729,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
20,24619,10058,4,30.0,1,2,0.911876,-0.731971,1.658724,-0.001729,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
21,24620,10058,4,28.0,2,2,0.911876,-0.731971,1.658724,-0.001729,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
22,24621,10058,4,33.0,2,2,0.911876,-0.731971,1.658724,-0.001729,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
23,24622,10058,4,57.0,1,2,0.911876,-0.731971,0.363288,-0.001729,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
24,24623,10058,4,54.0,2,2,0.911876,-0.612327,0.666916,0.008636,...,-0.08698,-0.208239,-0.089681,-0.015601,0.975689,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
25,24624,10059,3,35.0,0,4,-0.473952,-0.612327,0.049218,0.568206,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
26,24625,2395,3,51.0,2,4,0.078013,-0.112599,0.471300,-0.261960,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
27,24626,10060,3,54.0,0,4,-0.473952,0.006103,-0.237736,-0.649846,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
28,24627,10061,2,65.0,1,7,-0.473952,-0.612327,0.189589,0.369727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161
29,24628,10061,3,24.0,1,2,-0.473952,-0.612327,1.050086,0.945727,...,-0.08698,-0.206005,-0.089681,-0.015601,-0.024311,-0.005402,-0.00054,-0.001621,-0.00054,-0.002161

In [23]:
df_s = pd.DataFrame(scale_ar,columns=df.columns[6:])
df_s
df_all = pd.concat([new_df,df_s[no_grp]],axis=1)
df_all

,id,id_property,category,area,floor,beds_basic,backyard,unit_bedroom_equipment,kitchen,unit_bathroom_equipment,...,in_cable_tv,un_view_river,breakfast,description_structure_frontname,description_structure_short,description_structure_long,un_view_park,minibar,meal_room_only,mosquito_net
0,24588,10043,3,100.0,2,4,0.359911,-0.612327,0.397342,0.369727,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
1,24589,10043,3,100.0,1,4,0.359911,-0.612327,-0.126305,0.314040,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
2,24590,10043,3,100.0,0,4,0.359911,-0.612327,0.295777,-0.261960,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
3,24593,10046,3,53.0,0,4,0.359911,0.006103,0.051845,-0.261960,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
4,24594,9098,3,65.0,0,4,0.359911,-0.731971,-0.262609,0.369727,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1846,24569,10032,3,95.0,2,6,-0.473952,1.076378,0.059139,1.307567,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,30.405592,-0.02325,-0.032889,-0.040291
1847,24570,10033,3,45.0,1,2,-0.473952,0.006103,-0.752906,-0.018159,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
1848,24571,10034,5,150.0,0,6,0.911876,-0.232243,-0.996236,-0.649846,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
1849,24572,10035,5,150.0,0,6,0.911876,-0.232243,-0.996236,-0.649846,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291
1850,24575,10039,4,178.0,0,6,0.911876,-0.612327,-1.311433,-0.251594,...,-0.046537,-0.02325,-0.052044,-0.061612,-0.057027,-0.052044,-0.032889,-0.02325,-0.032889,-0.040291

In [24]:
df_all.columns

Index(['id', 'id_property', 'category', 'area', 'floor', 'beds_basic',
       'backyard', 'unit_bedroom_equipment', 'kitchen',
       'unit_bathroom_equipment',
       ...
       'in_cable_tv', 'un_view_river', 'breakfast',
       'description_structure_frontname', 'description_structure_short',
       'description_structure_long', 'un_view_park', 'minibar',
       'meal_room_only', 'mosquito_net'],
      dtype='object', length=122)

In [25]:
#df_all.to_csv("gen_data/PCA_nogrps_122.csv")

In [26]:
df_all.describe()

,id,id_property,category,area,floor,beds_basic,backyard,unit_bedroom_equipment,kitchen,unit_bathroom_equipment,...,in_cable_tv,un_view_river,breakfast,description_structure_frontname,description_structure_short,description_structure_long,un_view_park,minibar,meal_room_only,mosquito_net
count,1851.000000,1851.000000,1851.000000,1851.000000,1851.000000,1851.000000,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03,...,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03,1.851000e+03
mean,20468.457050,7877.850351,3.057266,58.539438,0.525662,3.507293,1.043646e-16,-3.261692e-16,1.053242e-16,2.033939e-15,...,5.367053e-16,-2.559593e-16,1.344871e-15,6.714420e-16,-4.472831e-16,2.599592e-16,-4.977410e-16,-6.687279e-16,-4.824162e-16,-5.732029e-16
std,6542.573553,2789.882301,0.525012,35.565741,0.831648,1.756017,5.260024e-01,6.732867e-01,7.335843e-01,6.060272e-01,...,1.000270e+00,1.000270e+00,1.000270e+00,1.000270e+00,1.000270e+00,1.000270e+00,1.000270e+00,1.000270e+00,1.000270e+00,1.000270e+00
min,3623.000000,1817.000000,0.000000,0.000000,-1.000000,0.000000,-4.739524e-01,-8.506732e-01,-1.426983e+00,-6.519351e-01,...,-4.653680e-02,-2.324953e-02,-5.204382e-02,-6.161246e-02,-5.702659e-02,-5.204382e-02,-3.288869e-02,-2.324953e-02,-3.288869e-02,-4.029115e-02
25%,18657.500000,6440.000000,3.000000,35.000000,0.000000,2.000000,-4.739524e-01,-6.123272e-01,-5.551726e-01,-6.498460e-01,...,-4.653680e-02,-2.324953e-02,-5.204382e-02,-6.161246e-02,-5.702659e-02,-5.204382e-02,-3.288869e-02,-2.324953e-02,-3.288869e-02,-4.029115e-02
50%,23375.000000,9044.000000,3.000000,50.000000,0.000000,4.000000,-4.739524e-01,-1.053682e-01,1.592817e-02,-5.217409e-02,...,-4.653680e-02,-2.324953e-02,-5.204382e-02,-6.161246e-02,-5.702659e-02,-5.204382e-02,-3.288869e-02,-2.324953e-02,-3.288869e-02,-4.029115e-02
75%,24874.500000,10129.000000,3.000000,70.000000,1.000000,4.000000,3.599106e-01,6.317644e-01,4.851640e-01,3.697275e-01,...,-4.653680e-02,-2.324953e-02,-5.204382e-02,-6.161246e-02,-5.702659e-02,-5.204382e-02,-3.288869e-02,-2.324953e-02,-3.288869e-02,-4.029115e-02
max,25832.000000,10679.000000,5.000000,420.000000,4.000000,14.000000,9.143708e-01,1.076378e+00,1.760288e+00,1.375762e+00,...,2.148837e+01,4.301163e+01,1.921458e+01,1.623048e+01,1.753568e+01,1.921458e+01,3.040559e+01,4.301163e+01,3.040559e+01,2.481935e+01

0       0.294797
1       0.294797
2       0.294797
3       0.294797
4       0.294797
          ...
1846   -3.392161
1847    0.294797
1848    0.294797
1849    0.294797
1850    0.294797
Name: sattv, Length: 1851, dtype: float64